spring:
  application:
    name: spring

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,public/**


  datasource:
    url: jdbc:h2:tcp://192.168.0.254/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
